### ISSUE TITLE
Comment construire une entreprise ?

### ISSUE THREAD

**Issue by Mzaaa** [Lyeed/Framework_Tanoa_Life#67]
Bonsoir, je voulais savoir comment on peux construire une entreprise

**Comment by Lyeed** [comment]
Bonjour,

``There is no company on the map because players have to build it.
The player in charge of registering companies must have the license "coop_agri".
In order to create a company he has to press the interaction button (windows by default) while targeting the new CEO.
He will have an option in his interactions menu to create a company.
He has to specify the company type and its name.
When pressing enter a construction block will appear and players will be able to gather and put materials in it.
If you want to skip the construction part as admin you can while targeting the construction block, go to the admin app and press "construire" (build)
If you don't have access to the admin app you can register your UID and permissions here (https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Staff.hpp)``

**Comment by Mzaaa** [comment]
Merci !

**Comment by Mzaaa** [comment]
Excuse moi de te re déranger, mais ou achetons les licences pour les entreprises

**Comment by Lyeed** [comment]
Pour créer des entreprises ? Ou la licence de l'entreprise en question ?

**Comment by Lyeed** [comment]
Sans réponse, le problème doit être résolu.
Je te laisse refaire une nouvelle isssue si tu as de nouveau des questions concernant les entreprises.
