### ISSUE TITLE
Healp

### ISSUE THREAD

**Issue by MasonsOD** [Lyeed/Framework_Tanoa_Life#91]
Good afternoon, how to enable the administration menu. Alas, I did not find

**Comment by Lyeed** [comment]
Hi,

You have to modify this file : https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Staff.hpp

You need to create a class for yourself, inherit it from the rank you want.
Also, you have to include your GUID in the macro at the beginning of the file.

**Comment by MasonsOD** [comment]
Thanks installed but there is no menu for spawn items how to build a processing corporation and craft menu I also did not find

**Comment by MasonsOD** [comment]
Thanks installed but there is no menu for spawn items how to build a processing corporation and craft menu I also did not find

**Comment by Lyeed** [comment]
There is no company on the map because players have to build it. The player in charge of registering companies must have the license "coop_agri". In order to create a company he has to press the interaction button (windows by default) while targeting the new CEO. He will have an option in his interactions menu to create a company. He has to specify the company type and its name. When pressing enter a construction block will appear and players will be able to gather and put materials in it. If you want to skip the construction part as admin you can while targeting the construction block, go to the admin app and press "construire" (build) If you don't have access to the admin app you can register your UID and permissions here (https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Staff.hpp)

**Comment by MasonsOD** [comment]
as a player, where do I get the materials, as I understand it, without the initial companies they are not? resources cannot be recycled, for example, into processed boards or doors. And also it’s not clear whether there is a player’s prison here, you can search to tie but how to land? Thanks for the quick answers and help.

**Comment by MasonsOD** [comment]
and how can a player get lecenzia. Or it should be issued by the administrator. There are also no places where you can get the resources necessary for building

**Comment by Lyeed** [comment]
> as a player, where do I get the materials, as I understand it, without the initial companies they are not?

Server's owner would have to construct and recruit in some key companies that are mandatory to the economy

> and how can a player get lecenzia. Or it should be issued by the administrator.

Which license are you talking about ? If you are talking about the one that is needed to create a company, then yes, the administrator would have to give it to someone he trusts. That player would have to handle all the new company regristrations and creations.

> And also it’s not clear whether there is a player’s prison here, you can search to tie but how to land

I didn't understand your question about the prison.
Currently implemented prison system has not been finished and therefor does not work.

**Comment by MasonsOD** [comment]
thanks for the help
